// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockControlV2DL;

#nullable disable

namespace StockControlV2DL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockControlV2EL.Models.CPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ClockSpeed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CoreCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CPUs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandType = "Intel CPU",
                            ClockSpeed = 3.6m,
                            CoreCount = 8,
                            CreatedDate = new DateTime(2024, 8, 13, 16, 9, 40, 446, DateTimeKind.Local).AddTicks(1742),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("StockControlV2EL.Models.GPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoreClock")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Memory")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GPUs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandType = "Asus GPU",
                            CoreClock = 1600,
                            CreatedDate = new DateTime(2024, 8, 13, 16, 9, 40, 446, DateTimeKind.Local).AddTicks(1836),
                            IsDeleted = false,
                            Memory = 8
                        });
                });

            modelBuilder.Entity("StockControlV2EL.Models.MotherBoard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("MotherBoards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandType = " Gigabyte MotherBoard",
                            CreatedDate = new DateTime(2024, 8, 13, 16, 9, 40, 446, DateTimeKind.Local).AddTicks(1864),
                            FormFactor = "ATX",
                            IsDeleted = false,
                            Socket = "LGA1151"
                        });
                });

            modelBuilder.Entity("StockControlV2EL.Models.RAM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RAMs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandType = "Corsair Ram",
                            Capacity = 16,
                            CreatedDate = new DateTime(2024, 8, 13, 16, 9, 40, 446, DateTimeKind.Local).AddTicks(1850),
                            IsDeleted = false,
                            Speed = 3200
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
